### ISSUE TITLE
mapSize does not take into account playable area

### ISSUE THREAD

**Issue by bsubei** [Thomas-Smyth/squad-layers#11]
e.g. for Skirmish layers (small playable area) of larger maps, the `mapSize` is the same as the regular layers.

I realize this may be intentional, in which case consider this a feature request.

**Comment by bsubei** [comment]
I just realized you source all the layers info from a google spreadsheet (over which you probably have no control), in which case you can't enter the playable area size yourself... :(

**Comment by Thomas-Smyth** [comment]
Information regarding playable area size is not available via our primary data source (the layer info spreadsheets released by OWI) and would be hard to represent given the irregular shape of playable areas.

To my knowledge, few non-Skirmish layers limit the playable area which is why we still consider it during our estimated of min and max player counts suitable for each layer.
